#! /bin/sh
# picom &
pgrep -x sxhkd > /dev/null || sxhkd &
#xrandr --query | grep " connected" | cut -d" " -f1 | xargs -I {} vibrant-cli {} 2.0 &
#sudo rm -rf /etc/xdg/autostart
#xwinwrap -ov -ni -g 1920x1080 -- mpv --wid=%WID --loop-file --no-audio --hwdec=vaapi --vo=gpu --profile=fast --framedrop=vo --demuxer-max-bytes=50M "Videos/livewall/1.mp4" &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          1

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc rule -a konsole state=floating
bspc config focused_border_color "#595959"
bspc config normal_border_color "#595959"
bspc config top_padding 0

polybar &
